/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 04 15:32:50 GMT 2025
 */

package Vintage.qql;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Vintage.qql.Sapatilha;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Sapatilha_ESTest extends Sapatilha_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      Sapatilha sapatilha1 = new Sapatilha(0, false, "", 1, false);
      boolean boolean0 = sapatilha0.equals(sapatilha1);
      assertEquals(0, sapatilha0.getTamanho());
      assertFalse(sapatilha1.getAtacadores());
      assertFalse(sapatilha0.isPremium());
      assertFalse(boolean0);
      assertEquals(1, sapatilha1.getAnoLancamento());
      assertFalse(sapatilha1.equals((Object)sapatilha0));
      assertEquals(0, sapatilha1.getTamanho());
      assertFalse(sapatilha1.isPremium());
      assertFalse(sapatilha0.getAtacadores());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      Sapatilha sapatilha1 = new Sapatilha(0, true, "c\u00F3digo: 0, nome: , descri\u00E7\u00E3o: , marca: , pre\u00E7o base: 0.0, corre\u00E7\u00E3o de pre\u00E7o: 0.0, novo: true, n\u00FAmero de donos: 0, condi\u00E7\u00E3o: , transportadora: , vendedor: , tipo: sapatilha, tamanho: 0, possui atacadores: false, cor: , ano de lan\u00E7amento: 0, premium: false", (-67), false);
      boolean boolean0 = sapatilha0.equals(sapatilha1);
      assertFalse(sapatilha0.isPremium());
      assertEquals(0, sapatilha0.getAnoLancamento());
      assertTrue(sapatilha1.getAtacadores());
      assertFalse(sapatilha1.isPremium());
      assertEquals((-67), sapatilha1.getAnoLancamento());
      assertEquals(0, sapatilha1.getTamanho());
      assertFalse(boolean0);
      assertFalse(sapatilha0.getAtacadores());
      assertEquals(0, sapatilha0.getTamanho());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Integer integer0 = new Integer((-69));
      Sapatilha sapatilha0 = new Sapatilha("gW3q-", (String) null, "{`QiBmS9PoCHOT#cD", integer0, (-69), (-69), false, (-69), "{`QiBmS9PoCHOT#cD", "h(DE2qQ>ZHi)0VN_", (-69), "", (-69), false, "zTWSN.y{chjWvrz7~.u", 0, false);
      float float0 = sapatilha0.calcularPrecoFinal();
      assertEquals((-69.0F), sapatilha0.getPrecoFinal(), 0.01F);
      assertEquals((-69.0F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha((-1095), false, "ps", 1, true);
      boolean boolean0 = sapatilha0.isPremium();
      assertEquals((-1095), sapatilha0.getTamanho());
      assertEquals(1, sapatilha0.getAnoLancamento());
      assertFalse(sapatilha0.getAtacadores());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setTamanho(1431);
      int int0 = sapatilha0.getTamanho();
      assertEquals(1431, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Integer integer0 = new Integer((-69));
      Sapatilha sapatilha0 = new Sapatilha("gW3q-", (String) null, "{`QiBmS9PoCHOT#cD", integer0, (-69), (-69), false, (-69), "{`QiBmS9PoCHOT#cD", "h(DE2qQ>ZHi)0VN_", (-69), "", (-69), false, "zTWSN.y{chjWvrz7~.u", 0, false);
      int int0 = sapatilha0.getTamanho();
      assertEquals(0, sapatilha0.getAnoLancamento());
      assertEquals((-69), int0);
      assertEquals("zTWSN.y{chjWvrz7~.u", sapatilha0.getCor());
      assertFalse(sapatilha0.isPremium());
      assertFalse(sapatilha0.getAtacadores());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha((-1294), false, ", vendedor: ", (-1294), false);
      sapatilha0.setCor((String) null);
      sapatilha0.getCor();
      assertFalse(sapatilha0.getAtacadores());
      assertEquals((-1294), sapatilha0.getAnoLancamento());
      assertFalse(sapatilha0.isPremium());
      assertEquals((-1294), sapatilha0.getTamanho());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha(1568, true, ">78Ab2(;&8[F]T}a=K", 1568, true);
      sapatilha0.getCor();
      assertEquals(1568, sapatilha0.getAnoLancamento());
      assertEquals(1568, sapatilha0.getTamanho());
      assertTrue(sapatilha0.isPremium());
      assertTrue(sapatilha0.getAtacadores());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Integer integer0 = new Integer(1);
      Sapatilha sapatilha0 = new Sapatilha("", "", ", cor: ", integer0, 0.0F, 16.4F, false, 1, "y", ", cor: ", 1, "", 1, false, "", 185, false);
      int int0 = sapatilha0.getAnoLancamento();
      assertEquals("", sapatilha0.getCor());
      assertFalse(sapatilha0.isPremium());
      assertEquals(1, sapatilha0.getTamanho());
      assertEquals(185, int0);
      assertFalse(sapatilha0.getAtacadores());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha((-1), true, "", (-1), false);
      int int0 = sapatilha0.getAnoLancamento();
      assertEquals((-1), sapatilha0.getTamanho());
      assertFalse(sapatilha0.isPremium());
      assertEquals((-1), int0);
      assertTrue(sapatilha0.getAtacadores());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha(1, true, ", novo: ", 1, true);
      sapatilha0.calcularPrecoFinal();
      sapatilha0.clone();
      assertEquals(4026.0F, sapatilha0.getPrecoFinal(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setPrecoFinal((-949.0F));
      Sapatilha sapatilha1 = sapatilha0.clone();
      assertEquals(0, sapatilha1.getAnoLancamento());
      assertFalse(sapatilha1.isPremium());
      assertEquals(0, sapatilha1.getTamanho());
      assertTrue(sapatilha1.equals((Object)sapatilha0));
      assertFalse(sapatilha1.getAtacadores());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Integer integer0 = new Integer((-5733));
      Sapatilha sapatilha0 = new Sapatilha(",FjI)", ",FjI)", ",FjI)", integer0, 3406.805F, (-5733), false, (-5733), "Y;r", "tdS(Vo,Y#IMaQAH==R", (-1610612734), "tdS(Vo,Y#IMaQAH==R", (-1411), false, ",FjI)", (-1), false);
      Sapatilha sapatilha1 = sapatilha0.clone();
      assertFalse(sapatilha1.getAtacadores());
      assertEquals((-1), sapatilha1.getAnoLancamento());
      assertTrue(sapatilha1.equals((Object)sapatilha0));
      assertEquals(",FjI)", sapatilha1.getCor());
      assertEquals((-1411), sapatilha0.getTamanho());
      assertFalse(sapatilha1.isPremium());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setCustosExpedicao(397.0F);
      Sapatilha sapatilha1 = sapatilha0.clone();
      assertFalse(sapatilha1.isPremium());
      assertEquals(0, sapatilha1.getAnoLancamento());
      assertFalse(sapatilha1.getAtacadores());
      assertEquals(0, sapatilha1.getTamanho());
      assertTrue(sapatilha1.equals((Object)sapatilha0));
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha(0, false, (String) null, 0, false);
      sapatilha0.setCustosExpedicao((-2569.37F));
      Sapatilha sapatilha1 = sapatilha0.clone();
      assertEquals(0, sapatilha1.getTamanho());
      assertFalse(sapatilha1.getAtacadores());
      assertEquals(0, sapatilha1.getAnoLancamento());
      assertFalse(sapatilha1.isPremium());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha((-1095), false, "ps", 1, true);
      sapatilha0.setCorrecaoPreco(1);
      Sapatilha sapatilha1 = sapatilha0.clone();
      assertTrue(sapatilha1.isPremium());
      assertFalse(sapatilha1.getAtacadores());
      assertEquals((-1095), sapatilha1.getTamanho());
      assertEquals(1, sapatilha1.getAnoLancamento());
      assertTrue(sapatilha1.equals((Object)sapatilha0));
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Sapatilha sapatilha0 = new Sapatilha((String) null, "&DOyJVE_2+SN nd", "&DOyJVE_2+SN nd", integer0, 0.0F, 0.0F, true, 344, ", transportadora: ", "EH7T|\"2C'T", 344, "", 955, true, "", 955, true);
      Sapatilha sapatilha1 = sapatilha0.clone();
      assertEquals(955, sapatilha1.getTamanho());
      assertTrue(sapatilha1.getAtacadores());
      assertEquals(955, sapatilha1.getAnoLancamento());
      assertTrue(sapatilha0.isPremium());
      assertTrue(sapatilha1.equals((Object)sapatilha0));
      assertEquals("", sapatilha1.getCor());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      Sapatilha sapatilha0 = new Sapatilha("p!l]_Pa)T( =K%FG", ",=", "p!l]_Pa)T( =K%FG", integer0, (-2324.0F), (-1), false, (-1), (String) null, "c\u00F3digo: ", 0, (String) null, (-1), false, "", (-1), false);
      Sapatilha sapatilha1 = sapatilha0.clone();
      assertEquals("", sapatilha1.getCor());
      assertFalse(sapatilha1.isPremium());
      assertEquals((-1), sapatilha1.getAnoLancamento());
      assertFalse(sapatilha1.getAtacadores());
      assertTrue(sapatilha1.equals((Object)sapatilha0));
      assertEquals((-1), sapatilha1.getTamanho());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Integer integer0 = new Integer((-3690));
      Sapatilha sapatilha0 = new Sapatilha("r", "r", "r", integer0, (-3690), 0.0F, false, 914, "r", "r", 2514, "r", (-3690), false, "r", 0, false);
      float float0 = sapatilha0.calcularPrecoFinal();
      assertEquals((-3685.963F), sapatilha0.getPrecoFinal(), 0.01F);
      assertEquals((-3685.963F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Sapatilha sapatilha0 = null;
      try {
        sapatilha0 = new Sapatilha((Sapatilha) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Vintage.qql.Artigo", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Integer integer0 = new Integer((-69));
      Sapatilha sapatilha0 = new Sapatilha("gW3q-", (String) null, "{`QiBmS9PoCHOT#cD", integer0, (-69), (-69), false, (-69), "{`QiBmS9PoCHOT#cD", "h(DE2qQ>ZHi)0VN_", (-69), "", (-69), false, "zTWSN.y{chjWvrz7~.u", 0, false);
      int int0 = sapatilha0.getAnoLancamento();
      assertEquals((-69), sapatilha0.getTamanho());
      assertEquals(0, int0);
      assertFalse(sapatilha0.isPremium());
      assertEquals("zTWSN.y{chjWvrz7~.u", sapatilha0.getCor());
      assertFalse(sapatilha0.getAtacadores());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      boolean boolean0 = sapatilha0.isPremium();
      assertFalse(boolean0);
      assertEquals(0, sapatilha0.getTamanho());
      assertEquals(0, sapatilha0.getAnoLancamento());
      assertFalse(sapatilha0.getAtacadores());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.getCor();
      assertEquals(0, sapatilha0.getAnoLancamento());
      assertFalse(sapatilha0.isPremium());
      assertEquals(0, sapatilha0.getTamanho());
      assertFalse(sapatilha0.getAtacadores());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      int int0 = sapatilha0.getTamanho();
      assertFalse(sapatilha0.isPremium());
      assertFalse(sapatilha0.getAtacadores());
      assertEquals(0, sapatilha0.getAnoLancamento());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      boolean boolean0 = sapatilha0.getAtacadores();
      assertEquals(0, sapatilha0.getAnoLancamento());
      assertFalse(boolean0);
      assertFalse(sapatilha0.isPremium());
      assertEquals(0, sapatilha0.getTamanho());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      Sapatilha sapatilha1 = new Sapatilha(0, false, "", 0, true);
      boolean boolean0 = sapatilha0.equals(sapatilha1);
      assertFalse(sapatilha1.getAtacadores());
      assertEquals(0, sapatilha1.getTamanho());
      assertEquals(0, sapatilha0.getTamanho());
      assertFalse(sapatilha0.getAtacadores());
      assertEquals(0, sapatilha0.getAnoLancamento());
      assertEquals(0, sapatilha1.getAnoLancamento());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setAnoLancamento(1);
      Sapatilha sapatilha1 = new Sapatilha();
      boolean boolean0 = sapatilha0.equals(sapatilha1);
      assertEquals(1, sapatilha0.getAnoLancamento());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      Sapatilha sapatilha1 = new Sapatilha(0, false, "Y", 0, false);
      boolean boolean0 = sapatilha0.equals(sapatilha1);
      assertFalse(sapatilha0.isPremium());
      assertEquals(0, sapatilha1.getTamanho());
      assertEquals(0, sapatilha1.getAnoLancamento());
      assertFalse(sapatilha1.getAtacadores());
      assertFalse(sapatilha1.isPremium());
      assertEquals(0, sapatilha0.getTamanho());
      assertFalse(sapatilha0.getAtacadores());
      assertEquals(0, sapatilha0.getAnoLancamento());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setCor((String) null);
      Sapatilha sapatilha1 = sapatilha0.clone();
      assertTrue(sapatilha1.equals((Object)sapatilha0));
      
      sapatilha1.setCor("c\u00F3digo: 0, nome: , descri\u00E7\u00E3o: , marca: , pre\u00E7o base: 0.0, corre\u00E7\u00E3o de pre\u00E7o: 0.0, novo: true, n\u00FAmero de donos: 0, condi\u00E7\u00E3o: , transportadora: , vendedor: , tipo: sapatilha, tamanho: 0, possui atacadores: true, cor: null, ano de lan\u00E7amento: 0, premium: false");
      boolean boolean0 = sapatilha0.equals(sapatilha1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      Sapatilha sapatilha1 = new Sapatilha(sapatilha0);
      boolean boolean0 = sapatilha0.equals(sapatilha1);
      assertFalse(sapatilha1.isPremium());
      assertEquals(0, sapatilha1.getAnoLancamento());
      assertEquals(0, sapatilha1.getTamanho());
      assertFalse(sapatilha1.getAtacadores());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      Sapatilha sapatilha1 = new Sapatilha(0, true, "c\u00F3digo: 0, nome: , descri\u00E7\u00E3o: , marca: , pre\u00E7o base: 0.0, corre\u00E7\u00E3o de pre\u00E7o: 0.0, novo: true, n\u00FAmero de donos: 0, condi\u00E7\u00E3o: , transportadora: , vendedor: , tipo: sapatilha, tamanho: 0, possui atacadores: false, cor: , ano de lan\u00E7amento: 0, premium: false", (-67), true);
      assertEquals(0, sapatilha1.getTamanho());
      
      sapatilha1.setTamanho((-67));
      boolean boolean0 = sapatilha1.equals(sapatilha0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Sapatilha sapatilha0 = new Sapatilha("", "", "", integer0, 0, 0, false, 312, "", "", 312, "", 312, false, "", 0, false);
      Sapatilha sapatilha1 = new Sapatilha("", "", "", integer0, 0, 0, false, 312, "", "", 0, "", 0, false, "", 312, false);
      boolean boolean0 = sapatilha0.equals(sapatilha1);
      assertFalse(sapatilha1.getAtacadores());
      assertEquals(0, sapatilha1.getTamanho());
      assertEquals(312, sapatilha0.getTamanho());
      assertFalse(boolean0);
      assertEquals(312, sapatilha1.getAnoLancamento());
      assertEquals(0, sapatilha0.getAnoLancamento());
      assertFalse(sapatilha1.isPremium());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      boolean boolean0 = sapatilha0.equals("c\u00F3digo: 0, nome: , descri\u00E7\u00E3o: , marca: , pre\u00E7o base: 0.0, corre\u00E7\u00E3o de pre\u00E7o: 0.0, novo: true, n\u00FAmero de donos: 0, condi\u00E7\u00E3o: , transportadora: , vendedor: , tipo: sapatilha, tamanho: 0, possui atacadores: false, cor: , ano de lan\u00E7amento: 0, premium: false");
      assertEquals(0, sapatilha0.getTamanho());
      assertFalse(sapatilha0.getAtacadores());
      assertEquals(0, sapatilha0.getAnoLancamento());
      assertFalse(boolean0);
      assertFalse(sapatilha0.isPremium());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      boolean boolean0 = sapatilha0.equals(sapatilha0);
      assertFalse(sapatilha0.getAtacadores());
      assertEquals(0, sapatilha0.getTamanho());
      assertTrue(boolean0);
      assertFalse(sapatilha0.isPremium());
      assertEquals(0, sapatilha0.getAnoLancamento());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      float float0 = sapatilha0.calcularPrecoFinal();
      assertEquals(0.0F, sapatilha0.getPrecoFinal(), 0.01F);
      assertEquals(0.0F, float0, 0.01F);
      assertFalse(sapatilha0.getAtacadores());
      assertEquals(0, sapatilha0.getTamanho());
      assertEquals(0, sapatilha0.getAnoLancamento());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setPremium(true);
      float float0 = sapatilha0.calcularPrecoFinal();
      assertEquals(4028.0F, sapatilha0.getPrecoFinal(), 0.01F);
      assertEquals(4028.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      assertFalse(sapatilha0.getAtacadores());
      
      sapatilha0.setAtacadores(true);
      boolean boolean0 = sapatilha0.getAtacadores();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      String string0 = sapatilha0.toString();
      assertEquals("c\u00F3digo: 0, nome: , descri\u00E7\u00E3o: , marca: , pre\u00E7o base: 0.0, corre\u00E7\u00E3o de pre\u00E7o: 0.0, novo: true, n\u00FAmero de donos: 0, condi\u00E7\u00E3o: , transportadora: , vendedor: , tipo: sapatilha, tamanho: 0, possui atacadores: false, cor: , ano de lan\u00E7amento: 0, premium: false", string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setCor((String) null);
      Sapatilha sapatilha1 = sapatilha0.clone();
      boolean boolean0 = sapatilha1.equals(sapatilha0);
      assertTrue(boolean0);
      assertEquals(0, sapatilha1.getAnoLancamento());
      assertFalse(sapatilha1.getAtacadores());
      assertEquals(0, sapatilha1.getTamanho());
      assertFalse(sapatilha1.isPremium());
  }
}
